---
# file: nginx/tasks/default_http.yml

- name: Enable Default Site
  file: >
    src='{{ nginx_root }}/sites-available/default'
    dest='{{ nginx_root }}/sites-enabled/default'
    state=link
  notify:
    - Reload Nginx
    - Open HTTP Ports