---
# file: nginx/tasks/default_https.yml

- name: Copy Public Key
  copy: 
    content: '{{ nginx_public_key }}'
    dest: '{{ nginx_root }}/certs/default.pem'
  notify:
    - Reload Nginx

- name: Copy Private Key
  copy:
    content: '{{ nginx_private_key }}'
    dest: '{{ nginx_root }}/certs/default-key.pem'
  notify:
    - Reload Nginx

    
- name: Enable Default Site
  file: >
    src='{{ nginx_root }}/sites-available/default_https'
    dest='{{ nginx_root }}/sites-enabled/default_https'
    state=link
  notify:
    - Reload Nginx
