---
# file: nginx/tasks/main.yml

- name: Install from Nginx.org mainline
  include: mainline.yml
  when: nginx_install_mainline
  tags:
    - nginx

- name: Install Packages
  apt: >
    pkg={{ item }}
    state=latest
  with_items:
    - nginx-light
  when: not nginx_install_mainline
  notify:
    - Restart Nginx
  tags:
    - nginx
    
- name: Create directorys
  file:
    path: '{{ item }}' 
    owner: root
    group: root
    mode: 0644
    state: directory
  with_items:
    - '{{ nginx_root }}/includes'
    - '{{ nginx_root }}/includes/directives-only'
  tags:
    - nginx


- name: Copy Nginx Base Config
  copy:
    src: '{{ item }}'
    dest: '{{ nginx_root }}/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_fileglob:
        - etc_nginx/*
  notify:
    - Reload Nginx
  tags:
    - nginx

- name: Enable Default Site
  include: default_http.yml
  when: nginx_enable_default_http
  tags:
    - nginx
  
- name: Create certs dir
  file: >
    path={{ nginx_root }}/certs
    owner=root
    group=root
    mode='0644'
    state=directory
  tags:
    - nginx
  
- name: Enable Default https Site
  include: default_https.yml
  when: nginx_enable_default_https
  tags:
    - nginx
  
- name: Start Nginx
  service: name=nginx state=started enabled=yes
  tags:
    - nginx
