---
# file: nginx/tasks/main.yml

- name: Install from Nginx.org Mainline
  include: install_mainline.yml
  when: nginx_install_type == 'mainline'
  tags:
    - nginx
    
- name: Install from Ubunut Default Sources
  include: install_ubuntu.yml
  when: nginx_install_type == 'ubuntu'
  tags:
    - nginx
    
- name: Copy Nginx Base Config
  copy:
    src: 'etc_nginx/'
    dest: '{{ nginx_root }}'
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload Nginx
  tags:
    - nginx
    
- name: Disable Sendfile
  lineinfile: 
    dest: '/etc/nginx/nginx.conf'
    regexp: '^\s*sendfile'
    line: 'sendfile off;'
    state: present
  when: not nginx_sendfile|bool

- name: Enable Default Site
  include: default_http.yml
  when: nginx_enable_default_http
  tags:
    - nginx

- name: Enable Default https Site
  include: default_https.yml
  when: nginx_enable_default_https
  tags:
    - nginx
  
- name: Start Nginx
  service: 
    name: nginx 
    state: started 
    enabled: yes
  tags:
    - nginx
