---
# file: nginx/tasks/main.yml

- name: Install Packages
  apt: >
    pkg={{ item }}
    state=latest
  with_items:
    - nginx-light
  notify:
    - Restart Nginx

- name: Copy Nginx Base Config
  copy: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root
    group=root
    mode=0644
  with_items:
        - { src: 'nginx.conf',                    dest: '{{ nginx_root }}/nginx.conf' }
        - { src: 'mime.types',                    dest: '{{ nginx_root }}/mime.types' }
        - { src: 'fastcgi_params',                dest: '{{ nginx_root }}/fastcgi_params' }
        - { src: 'sites-available/default',       dest: '{{ nginx_root }}/sites-available/default' }
        - { src: 'sites-available/default_https', dest: '{{ nginx_root }}/sites-available/default_https' }
        - { src: 'conf.d/common.conf',            dest: '{{ nginx_root }}/conf.d/common.conf' }
        - { src: 'conf.d/hide-headers.conf',      dest: '{{ nginx_root }}/conf.d/hide-headers.conf' }
  notify:
    - Reload Nginx

- name: Enable Default Site
  include: default_http.yml
  when: nginx_enable_default_http
  
- name: Enable Default https Site
  include: default_https.yml
  when: nginx_enable_default_https
  
- name: Start Nginx
  service: name=nginx state=started enabled=yes
